apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moviecstar
  labels:
    app: moviecstar
spec:
  serviceName: moviecstar
  replicas: 3
  selector:
    matchLabels:
      app: moviecstar
  template:
    metadata:
      labels:
        app: moviecstar
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: moviecstar
        image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio-prod/infra_cassandra:v13
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 4Gi
          requests:
           cpu: "300m"
           memory: 2Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "moviecstar-0.moviecstar.movieapp.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "K8Demo"
          - name: CASSANDRA_DC
            value: "DC1-K8Demo"
          - name: CASSANDRA_RACK
            value: "Rack1-K8Demo"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: moviecstar-data
          mountPath: /cassandra_data
  volumeClaimTemplates:
  - metadata:
      name: moviecstar-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: alicloud-disk-ssd
      resources:
        requests:
          storage: 20Gi
